"""Markdown report generator for GrowthLint."""

from __future__ import annotations

from datetime import datetime

from growthlint.models import AuditReport, RuleViolation


def generate_markdown(report: AuditReport) -> str:
    """Generate a shareable markdown audit report."""
    lines: list[str] = []

    # Header
    lines.append(f"# GrowthLint Audit Report")
    lines.append("")
    lines.append(f"**Target:** {report.target}")
    lines.append(f"**Date:** {report.scan_date or datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Platform:** {report.platform}")
    lines.append(f"**Pages Scanned:** {report.pages_scanned}")
    lines.append("")

    # Score Card
    lines.append("---")
    lines.append("")
    lines.append("## Growth Health Score")
    lines.append("")
    score = report.score
    lines.append(f"### {_score_emoji(score.grade)} {score.score}/100 (Grade: {score.grade})")
    lines.append("")

    if score.revenue_leak_estimate:
        lines.append(f"**Revenue Impact:** {score.revenue_leak_estimate}")
        lines.append("")

    # Summary counts
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")
    lines.append(f"| Critical | {score.critical_count} |")
    lines.append(f"| Warning  | {score.warning_count} |")
    lines.append(f"| Info     | {score.info_count} |")
    lines.append(f"| **Total** | **{score.total_violations}** |")
    lines.append("")

    # Category breakdown
    if score.category_scores:
        lines.append("### Category Scores")
        lines.append("")
        lines.append("| Category | Score |")
        lines.append("|----------|-------|")
        for cat, cat_score in sorted(score.category_scores.items()):
            lines.append(f"| {cat.title()} | {_score_bar(cat_score)} {cat_score}/100 |")
        lines.append("")

    # Violations by severity
    lines.append("---")
    lines.append("")
    lines.append("## Findings")
    lines.append("")

    critical = [v for v in report.violations if v.severity == "critical"]
    warnings = [v for v in report.violations if v.severity == "warning"]
    infos = [v for v in report.violations if v.severity == "info"]

    if critical:
        lines.append("### Critical Issues")
        lines.append("")
        for v in critical:
            lines.extend(_format_violation(v))

    if warnings:
        lines.append("### Warnings")
        lines.append("")
        for v in warnings:
            lines.extend(_format_violation(v))

    if infos:
        lines.append("### Info")
        lines.append("")
        for v in infos:
            lines.extend(_format_violation(v))

    if not report.violations:
        lines.append("No issues found. Your site looks great!")
        lines.append("")

    # Action plan
    if critical or warnings:
        lines.append("---")
        lines.append("")
        lines.append("## Action Plan")
        lines.append("")
        lines.append("**Priority fixes (do these first):**")
        lines.append("")
        for i, v in enumerate(critical[:5], 1):
            lines.append(f"{i}. **{v.rule_name}** - {v.fix}")
        for i, v in enumerate(warnings[:3], len(critical[:5]) + 1):
            lines.append(f"{i}. **{v.rule_name}** - {v.fix}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by [GrowthLint](https://github.com/super0510/GrowthLint) - The ESLint for Growth Marketing*")

    return "\n".join(lines)


def _format_violation(v: RuleViolation) -> list[str]:
    """Format a single violation as markdown."""
    lines = []
    icon = {"critical": "🔴", "warning": "🟡", "info": "🔵"}.get(str(v.severity), "")
    lines.append(f"#### {icon} {v.rule_name}")
    lines.append("")
    if v.description:
        lines.append(f"> {v.description}")
        lines.append("")
    if v.details:
        lines.append(f"**Details:** {v.details}")
        lines.append("")
    if v.impact:
        lines.append(f"**Impact:** {v.impact}")
        lines.append("")
    if v.fix:
        lines.append(f"**Fix:** {v.fix}")
        lines.append("")
    return lines


def _score_emoji(grade: str) -> str:
    """Return an emoji for the grade."""
    if grade.startswith("A"):
        return "🟢"
    if grade.startswith("B"):
        return "🟡"
    if grade.startswith("C"):
        return "🟠"
    return "🔴"


def _score_bar(score: int) -> str:
    """Return a visual score bar."""
    filled = score // 10
    empty = 10 - filled
    return "█" * filled + "░" * empty
